"""Add color column to orders table

Revision ID: 63b942574eb8
Revises: be5d7900497d
Create Date: 2022-01-01 16:44:26.816644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b942574eb8'
down_revision = 'be5d7900497d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('color', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'color')
    # ### end Alembic commands ###
