"""Add orders table

Revision ID: a6318f1a0c78
Revises: 15b9fdb623a0
Create Date: 2021-12-28 20:34:14.424614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6318f1a0c78'
down_revision = '15b9fdb623a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('stl_url', sa.String(length=255), nullable=False),
    sa.Column('create_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('customer_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_pk'], ['customers.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
