"""Add cart table

Revision ID: be5d7900497d
Revises: 84b1773e9078
Create Date: 2021-12-31 13:38:45.651510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5d7900497d'
down_revision = '84b1773e9078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('customer_pk', sa.Integer(), nullable=True),
    sa.Column('product_pk', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='status'), nullable=True),
    sa.ForeignKeyConstraint(['customer_pk'], ['customers.pk'], ),
    sa.ForeignKeyConstraint(['product_pk'], ['products.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
