"""Add column shipped to cart

Revision ID: c6776a3e6548
Revises: ec9de0a610fe
Create Date: 2022-01-01 18:33:31.172093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = 'c6776a3e6548'
down_revision = 'ec9de0a610fe'
branch_labels = None
depends_on = None


def upgrade():
    shipped = postgresql.ENUM('yes', 'no', name='shipped')
    shipped.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('shipped', sa.Enum('yes', 'no', name='shipped'), nullable=True))
    # ### end Alembic commands ###


def downgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'shipped')
    # ### end Alembic commands ###
    shipped = postgresql.ENUM('yes', 'no', name='shipped')
    shipped.create(op.get_bind())
