"""Add address column to cart table

Revision ID: ec9de0a610fe
Revises: 63b942574eb8
Create Date: 2022-01-01 16:52:18.473850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9de0a610fe'
down_revision = '63b942574eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'address')
    # ### end Alembic commands ###
